version: "3.8"

services:
  app:
    build:
      context: .
    # env_file:
    #   - .env
    ports:
      - "8000:8000"

  webserver:
    build:
      context: /nginx
    ports:
      - "80:80"
    depends_on:
      - app
